SELECT * FROM continent WHERE name LIKE '%America'
UNION
SELECT * FROM continent WHERE code IN (3,5)
ORDER BY name ASC;

-- Where union, not recommended;
SELECT a.name AS country, b.name AS continent FROM country a, continent b
WHERE a.continent = b.code
ORDER BY a.name ASC;

-- Inner Join
SELECT a.name AS country, b.name AS continent FROM country a
INNER JOIN continent b
ON a.continent = b.code;

-- Altering table sequence for autogenerated
ALTER SEQUENCE continent_code_seq RESTART with 8;

-- Full outer join
SELECT a.name, a.continent AS continentCode, b.name AS continentName  FROM country a
FULL OUTER JOIN continent b
ON a.continent = b.code
ORDER BY a.name DESC;

-- Right outer join w/ Exclusion;
SELECT a.name, a.continent, b.name
FROM country a
RIGHT JOIN continent b 
ON a.continent = b.code
WHERE a.continent IS NULL;